### ISSUE TITLE
Documentation for load() is wrong

### ISSUE THREAD

**Issue by cirodrig** [yaml/pyyaml.org#15]
The documentation has many instances of `load` being called with one argument, which is invalid usage since release 6.0.  For instance, one example looks like this:

```
>>> stream = file('document.yaml', 'r')    # 'document.yaml' contains a single YAML document.
>>> yaml.load(stream)
```

This call of load does not work in release 6.0.

Also, the signature in the Reference section is incorrect.  The signature is given as `load(stream, Loader=Loader)` but the correct signature is `load(stream, Loader)`.

**Comment by Rosuav** [comment]
Replacing all examples of `yaml.load` with `yaml.safe_load` would make them functional again. Please can this be fixed?

**Comment by mattalxndr** [comment]
Is this project dead or something?

I had assumed it was the unofficial default yaml plugin for Python, but poking around in these issues, it seems like most of the examples in your [docs](https://pyyaml.org/wiki/PyYAMLDocumentation) (anything that calls `yaml.load(input)` with only a single argument) have been spitting errors for four years. 

```
    out = yaml.load("""
          ^^^^^^^^^^^^^
TypeError: load() missing 1 required positional argument: 'Loader'
python-BaseException

Process finished with exit code 1
```

https://github.com/yaml/pyyaml/issues/576

**Comment by ChrisBarker-NOAA** [comment]
What is up with the documentation?

Looks like this change occured almost three years ago, adn the docs are still completely out of date.

And they are also not helpful in deciding what Loader to use -- if there isn't going to be a default, there really should be guidance up front! Maybe something in the error message even.

Is there a new source of the docs?

https://github.com/yaml/pyyaml.org

looks like it hasn't been updated in 4 years -- which would explain things ...

**Comment by rafrafek** [comment]
I am very confused. Is PyYaml still working? For me none of the code works and I'm getting `Argument missing for parameter "Loader"` errors. Also the `print` function is using wrong syntax `SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?`.

@nitzmahone can you give us an update if PyYaml is abandoned? Are there any alternatives for parsing yaml files in Python?
